### ISSUE TITLE
ISIK-Kommentierung - Linkbezeichnung

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/ISiK-Sicherheit#87]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/b49d99d489f1a0dacbd1448eedd306723b4a353f/ImplementationGuide/markdown/Uebersicht.md?plain=1#LL7C6-L7C6

Der erwähnte Abschnitt heißt im Link "ISiK-Sicherheit: Autorisierung"

**Comment by JoshuaBolte** [comment]
Korrigiert.
